name: pmem.io
description: Persistent Memory Programming
url: https://pmem.io

highlighter: rouge

gems:
  - jekyll-mentions

defaults:
  -
    scope:
      path: ""                  # all files
    values:
      layout: "default"         # default layout is "default"

exclude: ['CNAME', 'LICENSE', 'README.md', 'Gemfile' ]
